/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package net.ukrcom.asblockwar;

/**
 *
 * @author olden
 */
public class progressDialog extends javax.swing.JDialog {

    /**
     * Creates new form progressDialog
     *
     */
    public progressDialog() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(400, 50));
        setModal(true);
        setName("dialogProgressBar"); // NOI18N
        setUndecorated(true);
        setOpacity(0.75F);
        setPreferredSize(new java.awt.Dimension(400, 50));
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        jProgressBar.setStringPainted(true);
        getContentPane().add(jProgressBar, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JProgressBar jProgressBar;
    // End of variables declaration//GEN-END:variables
}
